export RWX=true
export RWX_PARALLEL_INDEX=0
export RWX_PARALLEL_TOTAL=2
export RWX_PARALLEL_GROUP_CACHE_KEY=some-cache-key
export RWX_ACTOR=some-actor
export RWX_ACTOR_ID=some-actor-id
export RWX_RUN_URL=https://cloud.rwx.com/mint/some-org/runs/some-run-id
export RWX_TASK_URL=https://cloud.rwx.com/mint/some-org/tasks/some-task-id
export RWX_RUN_ID=some-run-id
export RWX_TASK_ID=some-task-id
export RWX_TASK_ATTEMPT_NUMBER=1
export RWX_RUN_TITLE=Some title
export RWX_GIT_REPOSITORY_URL=git@github.com:rwx-research/captain.git
export RWX_GIT_REPOSITORY_NAME=rwx-research/captain
export RWX_GIT_COMMIT_MESSAGE=Some commit message
export RWX_GIT_COMMIT_SHA=some-commit-sha
export RWX_GIT_REF=refs/heads/some-ref
export RWX_GIT_REF_NAME=some-ref
