linters:
  # Only run explicitly enabled linters
  disable-all: true
  # The list below includes pretty much all available linters from the "bugs",
  # "format", and "performance" categories. However, we don't use most of the
  # non-default "style", "comment", or "complexity" linters since they are often
  # very opinionated and don't lead to better code per-se. We also don't use
  # "musttag" or "perfsprint"
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - contextcheck
    - decorder
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - err113
    - exhaustive
    - fatcontext
    - forbidigo
    - gci
    - gocheckcompilerdirectives
    - gochecksumtype
    - gocritic
    - gofmt
    - gofumpt
    - goimports
    - gosec
    - gosimple
    - gosmopolitan
    - govet
    - ineffassign
    - lll
    - loggercheck
    - makezero
    - misspell
    - nilerr
    - nilnesserr
    - noctx
    - paralleltest
    - prealloc
    - protogetter
    - reassign
    - recvcheck
    - revive
    - rowserrcheck
    - spancheck
    - sqlclosecheck
    - staticcheck
    - testifylint
    - testpackage
    - typecheck
    - unused
    - wrapcheck
    - zerologlint

linters-settings:
  forbidigo:
    forbid:
      - 'fmt\.Errorf' # Use internal errors package instead.
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/rwx-research)
      - dot
  wrapcheck:
    ignoreSigRegexps:
      - errors\.WithDecoration\(
      - errors\.New.*Error\(

issues:
  exclude-rules:
    # Some of the rules can be relaxed for test files
    - path: _test\.go
      linters:
        - wrapcheck
    # Comments sometimes _have_ to be longer than the limit (e.g. URLs)
    - linters:
        - lll
      source: "^\\s*// "
    # Allow dot-imports for gomega and ginkgo
    - linters:
        - revive
      source: "gomega|ginkgo"
