linters:
  # Only run explicitly enabled linters
  disable-all: true
  # The list below includes pretty much all available linters from the "bugs",
  # "format", and "performance" categories. However, we don't use most of the
  # non-default "style", "comment", or "complexity" linters since they are often
  # very opinionated and don't lead to better code per-se.
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - contextcheck
    - decorder
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - exportloopref
    - forbidigo
    - gci
    - gocritic
    - goerr113
    - gofmt
    - gofumpt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nilerr
    - noctx
    - paralleltest
    - prealloc
    - reassign
    - revive
    - staticcheck
    - testpackage
    - typecheck
    - unused
    - wrapcheck

linters-settings:
  forbidigo:
    forbid:
      - 'fmt\.Errorf' # Use internal errors package instead.
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/rwx-research)
      - dot
  wrapcheck:
    ignoreSigRegexps:
      - errors\.New.*Error\(

issues:
  exclude-rules:
    # Some of the rules can be relaxed for test files
    - path: _test\.go
      linters:
        - wrapcheck
    # Comments sometimes _have_ to be longer than the limit (e.g. URLs)
    - linters:
        - lll
      source: "^// "
