steps:
  - label: "Functional Tests"
    command:
      - for ((i=1; i<=100000; i++)); do echo abcdef; done
    env:
      # disable integration tests that aren't using buildkite's inherited env
      ONLY_TEST_INHERITED_ENV: true
